services:
  db:
    image: postgres:16
    container_name: crm_db
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm
      POSTGRES_DB: crm
    ports:
      - "5433:5432"
    volumes:
      - crm_pgdata:/var/lib/postgresql/data

volumes:
  crm_pgdata:
