"""auth_user_organization

Revision ID: e390c617aceb
Revises: ce3b622728ad
Create Date: 2026-06-28 16:39:07.090404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e390c617aceb'
down_revision: Union[str, None] = 'ce3b622728ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEED_ORG_NAME = "Educational Institute"
SEED_ADMIN_NAME = "Admin"
SEED_ADMIN_EMAIL = "admin@example.com"
SEED_ADMIN_PASSWORD_HASH = (
    "$2b$12$l/BC/qGKdiFrAa.d4XCla.Qf/Y18xonu7NG8oPTMt9XbxcEKsv5ni"
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'admission', 'department_manager', 'finance', 'teacher', name='user_role', native_enum=False), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_org_id'), 'users', ['org_id'], unique=False)

    bind = op.get_bind()
    bind.execute(
        sa.text(
            "INSERT INTO organizations (id, name, is_active) VALUES (1, :name, true)"
        ),
        {"name": SEED_ORG_NAME},
    )
    bind.execute(
        sa.text(
            "INSERT INTO users (id, name, email, password_hash, role, department_id, is_active, org_id) "
            "VALUES (1, :name, :email, :password_hash, 'admin', NULL, true, 1)"
        ),
        {
            "name": SEED_ADMIN_NAME,
            "email": SEED_ADMIN_EMAIL,
            "password_hash": SEED_ADMIN_PASSWORD_HASH,
        },
    )
    bind.execute(sa.text("ALTER TABLE organizations ALTER COLUMN id RESTART WITH 2"))
    bind.execute(sa.text("ALTER TABLE users ALTER COLUMN id RESTART WITH 2"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_org_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
