"""person_crud

Revision ID: e76302243fa0
Revises: e390c617aceb
Create Date: 2026-06-28 16:58:26.938823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e76302243fa0'
down_revision: Union[str, None] = 'e390c617aceb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('prospect', 'lead', 'student', 'dormant', 'alumni', name='person_status', native_enum=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_people_org_id'), 'people', ['org_id'], unique=False)
    op.create_index(
        'uq_people_org_id_phone_not_null',
        'people',
        ['org_id', 'phone'],
        unique=True,
        postgresql_where=sa.text('phone IS NOT NULL'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_people_org_id_phone_not_null', table_name='people')
    op.drop_index(op.f('ix_people_org_id'), table_name='people')
    op.drop_table('people')
    # ### end Alembic commands ###
